### ISSUE TITLE
[Bug]Make sign a tradable block for vanilla shops.

### ISSUE THREAD

**Issue by devryb** [TheFantasyCraft/Forge-Permittor#14]
Players get a permission denied message when left clicking a quickshop sign in regions (even though they are still able to purchase items)  Can this be fixed at all?

dev.bukkit.org/bukkit-plugins/quickshop-notlikeme/

**Comment by thomas15v** [comment]
Hmmm. Are they clicking with their bare hands ? Or with an item?

**Comment by thomas15v** [comment]
Confirmed!

**Comment by thomas15v** [comment]
Should be fixed in 45cf8e7b3e7b7c8834e88df9594a0a3c3a9e752d

**Comment by devryb** [comment]
Latest version failing to load:

[17:17:31] [Server thread/INFO]: [Forge_Permittor] Failed to get nms values this protection will now disable
[17:17:31] [Server thread/WARN]: java.lang.NullPointerException
[17:17:31] [Server thread/WARN]: 	at com.fantasycraft.forgepermittor.nms.NMSResolver.<init>(NMSResolver.java:90)
[17:17:31] [Server thread/WARN]: 	at com.fantasycraft.forgepermittor.ForgePermittor.onEnable(ForgePermittor.java:68)
[17:17:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[17:17:31] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[17:17:31] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[17:17:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[17:17:31] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[17:17:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500)
[17:17:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474)
[17:17:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434)
[17:17:31] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
[17:17:31] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
[17:17:31] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by thomas15v** [comment]
Whooops. Me being stupid. getItemlist() to get a block :facepunch:.

**Comment by thomas15v** [comment]
038a9ad5bec11e4f3b2dfdad708e9cd9971bdbe4

**Comment by devryb** [comment]
Build server looks like its currently down, will check back later

**Comment by thomas15v** [comment]
Indeed, something is crashing it :/. Not sure what yet.

**Comment by thomas15v** [comment]
Oh well, shelllock got me ehm. I didn't updated my bash and they where mining coins on it. That was the reason of the downtime. I am getting a new buildserver up ASAP.

**Comment by thomas15v** [comment]
Should be back up again @devryb can u test and confirm?

**Comment by devryb** [comment]
HTTP ERROR 404

Problem accessing /job/Forge-Permittor/. Reason:

    Not Found

Powered by Jetty://

**Comment by thomas15v** [comment]
Looks fine for me :smile: http://ci.thomas15v.net/.

**Comment by devryb** [comment]
Ah thanks might want to change the download link on the main page of forge permittor github.
I tested it and it loads fine now however when using a shop I still get the error.

http://puu.sh/gK24g/592daf544a.png

**Comment by thomas15v** [comment]
Is this still an issue? I would like to close this one :+1:.

**Comment by devryb** [comment]
Not sure we no longer use this and no one else has complained here so I guess close :)
