### ISSUE TITLE
WorldGuard Incompatibility Error.

### ISSUE THREAD

**Issue by thegtz** [TheFantasyCraft/Forge-Permittor#19]
[18:33:19] [Server thread/ERROR]: Could not pass event EntityDamageByEntityEvent to ForgePermittor v0.3-BETA
org.bukkit.event.EventException
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEvent(CraftEventFactory.java:102) [CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:595) [CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:463) [CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:627) [CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
at net.minecraft.entity.EntityLivingBase.damageEntity_CB(EntityLivingBase.java:1364) [sv.class:?]
at net.minecraft.entity.player.EntityPlayer.damageEntity_CB(EntityPlayer.java:1228) [yz.class:?]
at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:903) [sv.class:?]
at net.minecraft.entity.player.EntityPlayer.func_70097_a(EntityPlayer.java:1144) [yz.class:?]
at net.minecraft.entity.player.EntityPlayerMP.func_70097_a(EntityPlayerMP.java:646) [mw.class:?]
at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1388) [yz.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1589) [nh.class:?]
at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244) [ej.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173) [nc.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
Caused by: java.lang.IncompatibleClassChangeError: Found interface com.sk89q.worldguard.protection.ApplicableRegionSet, but class was expected
at com.fantasycraft.forgepermittor.protection.plugins.WorldguardPlugin.CanDamage(WorldguardPlugin.java:61) ~[?:?]
at com.fantasycraft.forgepermittor.protection.ProtectionManager.CanDamage(ProtectionManager.java:79) ~[?:?]
at com.fantasycraft.forgepermittor.listeners.ProtectionListener.onEntityDamageByEntityEvent(ProtectionListener.java:75) ~[?:?]
at sun.reflect.GeneratedMethodAccessor293.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
... 23 more

**Comment by thomas15v** [comment]
Update worldguard to 6.0. And see what happens :).
Also make sure you use a dev build: http://ci.thomas15v.net.

**Comment by thegtz** [comment]
Got a different error now.

[21:07:15] [Server thread/ERROR]: Could not pass event BlockBreakEvent to Forge_Permittor v0.3-BETA
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callBlockBreakEvent(CraftEventFactory.java:1010) [CraftEventFactory.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at net.minecraftforge.event.world.BlockEvent$BreakEvent.<init>(BlockEvent.java:90) [BlockEvent$BreakEvent.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	at buildcraft.factory.BlockMiner.acceptEnergy(BlockMiner.java:94) [BlockMiner.class:?]
	at buildcraft.factory.TileQuarry.dig(TileQuarry.java:233) [TileQuarry.class:?]
	at buildcraft.factory.TileQuarry.func_145845_h(TileQuarry.java:191) [TileQuarry.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:2491) [ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_76]
Caused by: java.lang.IncompatibleClassChangeError: Found class com.sk89q.worldguard.protection.ApplicableRegionSet, but interface was expected
	at com.fantasycraft.forgepermittor.protection.plugins.WorldguardPlugin.BlockInProtectedLand(WorldguardPlugin.java:67) ~[?:?]
	at com.fantasycraft.forgepermittor.protection.ProtectionManager.BlockInProtectedLand(ProtectionManager.java:88) ~[?:?]
	at com.fantasycraft.forgepermittor.listeners.FakePlayerHandler.onBlockBreakEvent(FakePlayerHandler.java:28) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor58.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:git-Cauldron-MCPC-Plus-1.7.10-1.1307.06.218]
	... 15 more

**Comment by thegtz** [comment]
I think I might disable worldguard feature and just leave griefpreventionplus on as thats our main protection plugin.
