### ISSUE TITLE
Some log spam that seems to be happening

### ISSUE THREAD

**Issue by devryb** [TheFantasyCraft/Forge-Permittor#8]
I'm not sure what item is being used yet when this happens but will post here when I find it

[11:22:54] [Server thread/WARN]: java.lang.NullPointerException
[11:22:54] [Server thread/WARN]: 	at com.fantasycraft.forgepermittor.protection.plugins.GriefProtectionPlugin.CanUseItem(GriefProtectionPlugin.java:46)
[11:22:54] [Server thread/WARN]: 	at com.fantasycraft.forgepermittor.protection.ProtectionManager.CanUseItem(ProtectionManager.java:59)
[11:22:54] [Server thread/WARN]: 	at com.fantasycraft.forgepermittor.listeners.ProtectionListener.onPlayerInteractEvent(ProtectionListener.java:43)
[11:22:54] [Server thread/WARN]: 	at sun.reflect.GeneratedMethodAccessor226.invoke(Unknown Source)
[11:22:54] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:22:54] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:606)
[11:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334)
[11:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[11:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507)
[11:22:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492)
[11:22:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:223)
[11:22:54] [Server thread/WARN]: 	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:422)
[11:22:54] [Server thread/WARN]: 	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:875)
[11:22:54] [Server thread/WARN]: 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
[11:22:54] [Server thread/WARN]: 	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
[11:22:54] [Server thread/WARN]: 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:244)
[11:22:54] [Server thread/WARN]: 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:173)
[11:22:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
[11:22:54] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
[11:22:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
[11:22:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
[11:22:54] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by thomas15v** [comment]
Hmmm yeah without the item I can't do mutch to resolve this.

**Comment by thomas15v** [comment]
You can reopen it in case it hasn't been fixed :/.
